### ISSUE TITLE
Operator pod panics while removing the finalizer 

### ISSUE THREAD

**Issue by sp98** [alauda/topolvm-operator#17]
After deleting the cluster.yaml, the operator pod restarts with panic ` Observed a panic: "close of closed channel" (close of closed channel)` 

Steps to reproduce:
1.Setup a local K8s cluster.
2.Navigate to /deploy/example directory.
3. Run : kubectl create -f common.yaml
4. Run: Kubectl create -f crds.yaml
5. Run: Kubectl create -f opeartor.yaml
6. Run: Kubectl create -f cluster.yaml
7. Delete the cluster by running ` Kubectl delete -f cluster.yaml` 

Actual Behavior:
- Operator pod panics while removing the finalizer. 

Expected Behaivor: 
- Although the operator pod restarts, no error should be observed in the first place. 

Error:
```
2021-10-12 07:10:08.683645 D | topolvm-cluster-reconciler: start reconcile
2021-10-12 07:10:08.683691 I | topolvm-cluster-reconciler: deleting topolvm cluster "topolvmcluster-sample"
2021-10-12 07:10:08.683700 I | topolvm-spec: removing finalizer "topolvmcluster.topolvm.cybozu.com" on "topolvmcluster-sample"
E1012 07:10:08.816075       1 runtime.go:78] Observed a panic: "close of closed channel" (close of closed channel)
goroutine 213 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x173d060, 0x1ac9f50)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/runtime/runtime.go:48 +0x89
panic(0x173d060, 0x1ac9f50)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/alauda/topolvm-operator/controllers.(*TopolvmClusterReconciler).reconcile(0xc000255a40, 0xc000d4bfb0, 0xe, 0xc000a9ea60, 0x15, 0x0, 0x0, 0x173b440, 0x256bd20)
	/workdir/controllers/topolvmcluster_controller.go:186 +0xee5
github.com/alauda/topolvm-operator/controllers.(*TopolvmClusterReconciler).Reconcile(0xc000255a40, 0x1b1cc80, 0xc000cf25d0, 0xc000d4bfb0, 0xe, 0xc000a9ea60, 0x15, 0xc000cf25d0, 0x40be9f, 0xc000032000, ...)
	/workdir/controllers/topolvmcluster_controller.go:88 +0x6a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003fd2c0, 0x1b1cbc0, 0xc0001f0000, 0x17976c0, 0xc000431240)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:297 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003fd2c0, 0x1b1cbc0, 0xc0001f0000, 0xc000427e00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:252 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x1b1cbc0, 0xc0001f0000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:215 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000427f50)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00072df50, 0x1ae30a0, 0xc0001f5470, 0xc0001f0001, 0xc000634000)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000427f50, 0x3b9aca00, 0x0, 0x1, 0xc000634000)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1b1cbc0, 0xc0001f0000, 0xc000615580, 0x3b9aca00, 0x0, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1b1cbc0, 0xc0001f0000, 0xc000615580, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:212 +0x45e
panic: close of closed channel [recovered]
	panic: close of closed channel

goroutine 213 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x173d060, 0x1ac9f50)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/alauda/topolvm-operator/controllers.(*TopolvmClusterReconciler).reconcile(0xc000255a40, 0xc000d4bfb0, 0xe, 0xc000a9ea60, 0x15, 0x0, 0x0, 0x173b440, 0x256bd20)
	/workdir/controllers/topolvmcluster_controller.go:186 +0xee5
github.com/alauda/topolvm-operator/controllers.(*TopolvmClusterReconciler).Reconcile(0xc000255a40, 0x1b1cc80, 0xc000cf25d0, 0xc000d4bfb0, 0xe, 0xc000a9ea60, 0x15, 0xc000cf25d0, 0x40be9f, 0xc000032000, ...)
	/workdir/controllers/topolvmcluster_controller.go:88 +0x6a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003fd2c0, 0x1b1cbc0, 0xc0001f0000, 0x17976c0, 0xc000431240)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:297 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003fd2c0, 0x1b1cbc0, 0xc0001f0000, 0xc000427e00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:252 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x1b1cbc0, 0xc0001f0000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:215 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000427f50)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00072df50, 0x1ae30a0, 0xc0001f5470, 0xc0001f0001, 0xc000634000)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000427f50, 0x3b9aca00, 0x0, 0x1, 0xc000634000)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1b1cbc0, 0xc0001f0000, 0xc000615580, 0x3b9aca00, 0x0, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1b1cbc0, 0xc0001f0000, 0xc000615580, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:

```

**Comment by little-guy-lxr** [comment]
That is bug of topolvmcluster delete operation  . we are testing the fix. After test passes, will sync at soon
